apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-role
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "pods/exec", "pods/binding"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "exec", "connect", "bind"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: custom-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: custom-role
  apiGroup: rbac.authorization.k8s.io
